version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/image/Dockerfile
    image: spotify:latest
    command: hypercorn -b 0.0.0.0:5000 serve
    env_file: ./prod.env
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: ./docker/image/Dockerfile
    env_file: ./prod.env
    image: spotify:latest
    command: python worker.py
    depends_on:
      - redis
  redis:
    image: redis
    expose:
      - "${REDIS_PORT}"
    hostname: "${REDIS_HOST}"
